name: nix-buildkite
description: Generates a Buildkite pipeline from a Nix expression
author: https://github.com/hackworthltd
requirements: []
configuration:
    properties:
        expr:
            type: string
        post-build-hook:
            type: string
        agent-tags:
            type: string
    required:
        - expr
    not:
        required:
            - post-build-hook
            - agent-tags
    additionalProperties: false
