name: nix-buildkite
description: Generates a Buildkite pipeline from a Nix expression
author: https://github.com/hackworthltd
requirements: []
configuration:
  properties:
    file:
      type: string
    post-build-hook:
      type: string
    agent-tags:
      type: string
  required:
    - file
  not:
    required:
      - post-build-hook
      - agent-tags
  additionalProperties: false
