name: nix-buildkite
description: Generates a Buildkite pipeline from a Nix expression
author: https://github.com/hackworthltd
requirements: []
configuration:
    properties:
        expr:
            type: string
        nix-eval-jobs-args:
            type: string
        jq-opts:
            type: string
        jq-filter:
            type: string
        post-build-hook:
            type: string
        agent-tags:
            type: string
    required:
        - expr
    not:
        required:
            - nix-eval-jobs-args
            - jq-opts
            - jq-filter
            - post-build-hook
            - agent-tags
    additionalProperties: false
