agents:
    queue: "nix-eval"

steps:
    - command: nix flake archive .#
      label: ":nixos: Archive Nix flake inputs"
      agents:
          queue: "nix-build"

    - command: nix-buildkite
      label: ":nixos: :buildkite:"
      env:
          BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"
      plugins:
          - hackworthltd/nix#v2.0.0-b3:
                expr: ".#hydraJobs"
                use-nix-build: "true"
                attr-prefix: ".#hydraJobs."
                nix-eval-jobs-args: --workers 8 --max-memory-size 8GiB --flake --force-recurse
                agent-tags: queue=nix-build,os=linux

    - wait

    - label: ":nixos: :linux: Cache the Nix shell"
      command: |
          nix develop --print-build-logs --profile /tmp/primer --command echo "done"
      agents:
          queue: "nix-build"

    - label: ":nixos: :macos: Cache the Nix shell"
      command: |
          nix develop --print-build-logs --profile /tmp/primer --command echo "done"
      agents:
          queue: "nix-build"
          os: "darwin"
