agents:
  public: "true"
  os: "linux"

steps:
  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.2.0:
          id: hackworthltd/nix

  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - hackworthltd/nix:
          file: jobs.nix

  - command: nix flake archive .#
    label: ":nixos: Archive Nix flake inputs"
