#!/usr/bin/env bash
set -euo pipefail

NIX_FILE="$BUILDKITE_PLUGIN_NIX_FILE"
if [[ -n "${BUILDKITE_PLUGIN_NIX_POST_BUILD_HOOK:-}" ]]; then
    export POST_BUILD_HOOK="$BUILDKITE_PLUGIN_NIX_POST_BUILD_HOOK"
fi
if [[ -n "${BUILDKITE_PLUGIN_NIX_AGENT_TAGS:-}" ]]; then
    export AGENT_TAGS="$BUILDKITE_PLUGIN_NIX_AGENT_TAGS"
fi

echo "--- :nixos: Running nix-buildkite"
PIPELINE=$( nix run .#nix-buildkite -- "$NIX_FILE" )

echo "--- :pipeline: Uploading pipeline"
echo "$PIPELINE" | buildkite-agent pipeline upload
