#!/usr/bin/env bash
set -euo pipefail

NIX_EXPR="$BUILDKITE_PLUGIN_NIX_EXPR"
if [[ -n "${BUILDKITE_PLUGIN_NIX_POST_BUILD_HOOK:-}" ]]; then
    export POST_BUILD_HOOK="$BUILDKITE_PLUGIN_NIX_POST_BUILD_HOOK"
fi
if [[ -n "${BUILDKITE_PLUGIN_NIX_AGENT_TAGS:-}" ]]; then
    export AGENT_TAGS="$BUILDKITE_PLUGIN_NIX_AGENT_TAGS"
fi

echo "--- :nixos: Running nix-buildkite"
PIPELINE=$( nix-instantiate "$NIX_EXPR" | nix run 'github:hackworthltd/nix-buildkite-plugin?ref=v1.1.2#nix-buildkite' )

echo "--- :pipeline: Uploading pipeline"
echo "$PIPELINE" | buildkite-agent pipeline upload
